//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public string NUM_CLIENTE { get; set; }
        public string NOMBRE_CTE { get; set; }
        public string CLAVE_BAJA { get; set; }
        public Nullable<decimal> F_ALTA_CTE { get; set; }
        public Nullable<decimal> F_BAJA_CTE { get; set; }
        public string CADENA_DISTRI { get; set; }
        public Nullable<decimal> TIPO_CLIENTE { get; set; }
        public Nullable<decimal> TERRITORIO { get; set; }
        public Nullable<decimal> REGION { get; set; }
        public Nullable<decimal> CIUDAD { get; set; }
        public string CRED_ALTO { get; set; }
        public Nullable<decimal> F_CAPTURA { get; set; }
        public string DIMFINA03 { get; set; }
    }
}
