//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Imp
    {
        public string PUERTO { get; set; }
        public string NUM_ORDEN { get; set; }
        public Nullable<decimal> CAJAS { get; set; }
        public Nullable<decimal> CAJAS_ANT { get; set; }
        public string FLAG_B { get; set; }
        public string SELLO1 { get; set; }
        public string SELLO2 { get; set; }
    }
}
