//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtlPedidos
    {
        public string CustAccount { get; set; }
        public string ShipmentId { get; set; }
        public string PurchOrderFormNum { get; set; }
        public string OrderNum { get; set; }
        public string WorkId { get; set; }
        public string InventLocationId { get; set; }
        public Nullable<int> SalesStatus { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public Nullable<System.DateTime> ShippingDateRequested { get; set; }
        public Nullable<System.DateTime> LiberacionDateTime { get; set; }
        public string WNUM_PED_CTE { get; set; }
        public string NUM_ORDEN { get; set; }
        public string NUM_PED_CIA { get; set; }
        public string NUM_FACTURA { get; set; }
        public Nullable<decimal> FOLIO { get; set; }
        public string NUM_CLIENTE { get; set; }
        public Nullable<decimal> F_ENVIO_SURT { get; set; }
        public Nullable<decimal> HORA_SURTIDO { get; set; }
        public string ESTADO_PEDIDO { get; set; }
        public Nullable<decimal> F_CAPTURA { get; set; }
        public Nullable<decimal> F_PEDIDO { get; set; }
        public Nullable<decimal> F_PROGRAMADA { get; set; }
        public Nullable<decimal> FECHA_I_SUR { get; set; }
        public Nullable<decimal> HORA_I_SUR { get; set; }
        public Nullable<decimal> FECHA_F_SUR { get; set; }
        public Nullable<decimal> HORA_F_SUR { get; set; }
        public Nullable<decimal> F_RECHAZO { get; set; }
        public Nullable<decimal> F_VARIAS_01 { get; set; }
        public Nullable<decimal> F_VARIAS_03 { get; set; }
        public Nullable<decimal> F_VARIAS_02 { get; set; }
    }
}
