//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Error
    {
        public string OR_HOJA { get; set; }
        public string ORDEN_PROD { get; set; }
        public string NUM_ORDEN { get; set; }
        public string NUM_PRODUCTO { get; set; }
        public string SURTIDOR { get; set; }
        public string USUARIO { get; set; }
        public string PUERTO { get; set; }
        public string CLAVE_MOVTO { get; set; }
        public Nullable<decimal> UNI_SCANEADA { get; set; }
        public Nullable<decimal> F_SURTIDO { get; set; }
        public Nullable<decimal> CAJAS { get; set; }
        public string CODIGO_SEC { get; set; }
    }
}
