//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Hoja
    {
        public string OR_HOJA { get; set; }
        public string NUM_ORDEN { get; set; }
        public Nullable<int> HOJA { get; set; }
        public Nullable<decimal> FECHA_SUR { get; set; }
        public Nullable<decimal> HORA_I_SUR { get; set; }
        public Nullable<decimal> HORA_F_SUR { get; set; }
        public string SURTIDOR { get; set; }
    }
}
