//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Orden
    {
        public string CustAccount { get; set; }
        public string WorkId { get; set; }
        public string WMSLocationId { get; set; }
        public string ItemId { get; set; }
        public string LP { get; set; }
        public Nullable<decimal> QtyWork { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> WorkStatus { get; set; }
        public string NUM_CLIENTE { get; set; }
        public string NUM_ORDEN { get; set; }
        public string ORDEN_PROD { get; set; }
        public Nullable<decimal> UNI_PEDIDAS { get; set; }
        public Nullable<decimal> UNI_SURTIDA { get; set; }
        public Nullable<decimal> UNI_SCANEADA { get; set; }
        public Nullable<decimal> UNI_DIFE { get; set; }
        public string CLAVE_MOVTO { get; set; }
        public string CLAVE_BAJA { get; set; }
    }
}
