//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Scaner
    {
        public string NUM_ORDEN { get; set; }
        public string BARCODE { get; set; }
        public string NUM_PRODUCTO { get; set; }
        public Nullable<decimal> UNI_SCANEADA { get; set; }
        public string CLAVE_MOVTO { get; set; }
        public string CLAVE_BAJA { get; set; }
        public string SURTIDOR { get; set; }
        public Nullable<decimal> HORA_I_SUR { get; set; }
        public Nullable<decimal> HORA_F_SUR { get; set; }
        public Nullable<decimal> FECHA_SUR { get; set; }
        public Nullable<decimal> HOJA { get; set; }
        public Nullable<decimal> F_SURTIDO { get; set; }
        public Nullable<decimal> HORA_SURTIDO { get; set; }
        public string USUARIO { get; set; }
        public string PUERTO { get; set; }
        public Nullable<decimal> CAJAS { get; set; }
        public Nullable<decimal> T_CAJAS { get; set; }
        public string CODIGO_SEC { get; set; }
    }
}
