//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int DetallePedidoId { get; set; }
        public string CustAccount { get; set; }
        public string ShipmentId { get; set; }
        public string PurchOrderFormNum { get; set; }
        public string OrderNum { get; set; }
        public string WorkId { get; set; }
        public string InventLocationId { get; set; }
        public Nullable<int> SalesStatus { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public Nullable<System.DateTime> ShippingDateRequested { get; set; }
        public Nullable<System.DateTime> LiberacionDateTime { get; set; }
        public Nullable<System.DateTime> TransDateTime { get; set; }
        public string WMSLocationId { get; set; }
        public string ItemId { get; set; }
        public string inventBatchId { get; set; }
        public string LP { get; set; }
        public Nullable<decimal> QtyWork { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> WorkStatus { get; set; }
        public string NUM_PED_CIA { get; set; }
        public string LLAVE_LOC { get; set; }
        public string NUM_PRODUCTO { get; set; }
        public Nullable<decimal> UNI_PEDIDAS { get; set; }
        public Nullable<decimal> UNI_SURTIDA_SUG { get; set; }
        public Nullable<decimal> UNI_SURTIDA_REAL { get; set; }
        public string CLAVE_MOVTO { get; set; }
        public string CLAVE_BAJA { get; set; }
        public string MARCA { get; set; }
    }
}
