//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InicioSesion
    {
        public int InicioSesionID { get; set; }
        public int UsuarioID { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraTermino { get; set; }
        public int MinutosDeSesion { get; set; }
    }
}
