//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OperacionesAXEntities : DbContext
    {
        public OperacionesAXEntities()
            : base("name=OperacionesAXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<CtlPedidos> CtlPedidos { get; set; }
        public virtual DbSet<Det_Orden> Det_Orden { get; set; }
        public virtual DbSet<Orden_Contenedor> Orden_Contenedor { get; set; }
        public virtual DbSet<ProdAntera> ProdAntera { get; set; }
        public virtual DbSet<Control_Cajas> Control_Cajas { get; set; }
        public virtual DbSet<Control_Imp> Control_Imp { get; set; }
        public virtual DbSet<Det_Error> Det_Error { get; set; }
        public virtual DbSet<Det_Hoja> Det_Hoja { get; set; }
        public virtual DbSet<Det_Scaner> Det_Scaner { get; set; }
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<InicioSesion> InicioSesion { get; set; }
        public virtual DbSet<OrdenAsignada> OrdenAsignada { get; set; }
        public virtual DbSet<Surtidores> Surtidores { get; set; }
    
        public virtual int SumarizaEscaneo(string nC)
        {
            var nCParameter = nC != null ?
                new ObjectParameter("NC", nC) :
                new ObjectParameter("NC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SumarizaEscaneo", nCParameter);
        }
    }
}
