//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenAsignada
    {
        public int FOLIO_ASIGNADO { get; set; }
        public string NUM_ORDEN { get; set; }
        public string NUM_PED_CIA { get; set; }
        public string USUARIO { get; set; }
        public string STATUS { get; set; }
        public string MARCA { get; set; }
        public decimal TIPOSURTIDO { get; set; }
        public Nullable<System.DateTime> INICIOSURTIDO { get; set; }
        public Nullable<System.DateTime> TERMINASURTIDO { get; set; }
        public string SUBSTATUS1 { get; set; }
    }
}
