//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdAntera
    {
        public string CIA { get; set; }
        public string PROV { get; set; }
        public Nullable<decimal> LINEA { get; set; }
        public Nullable<decimal> GRUPO { get; set; }
        public string TIPO_ALMACEN { get; set; }
        public Nullable<decimal> SUBGRU { get; set; }
        public Nullable<decimal> SUBGRUPO { get; set; }
        public Nullable<decimal> AGRUP_VTAS { get; set; }
        public string BARCODE { get; set; }
        public Nullable<decimal> F_CAPTURA { get; set; }
        public string CLAVE_BAJA { get; set; }
        public string NUM_PRODUCTO { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<decimal> PRE_FACT_FRO { get; set; }
        public Nullable<decimal> PRE_PUB_FRO { get; set; }
        public Nullable<decimal> PRE_FACT { get; set; }
        public Nullable<decimal> PPUBSIVA { get; set; }
        public Nullable<decimal> PPUBCIVA { get; set; }
        public Nullable<decimal> FOB { get; set; }
        public Nullable<decimal> GTOSIMP { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string DESCON { get; set; }
        public string TIPOPROD { get; set; }
        public string CODSEGU { get; set; }
        public Nullable<decimal> PESO { get; set; }
    }
}
