//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.DBSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surtidores
    {
        public int UsuarioID { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string NombreSurtidor { get; set; }
        public int TipoSurtido { get; set; }
        public string NumEmpleado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> ScanerID { get; set; }
        public Nullable<int> AreaID { get; set; }
    }
}
