//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.WebServices.OperacionesAXContenedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContenedorDatos", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ContenedorDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private P2PMovil.WebServices.OperacionesAXContenedor.ContenedorProducto[] LineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sello1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sello2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WHSContainerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WHSContainerTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WHSShipmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenedor {
            get {
                return this.ContenedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenedorField, value) != true)) {
                    this.ContenedorField = value;
                    this.RaisePropertyChanged("Contenedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public P2PMovil.WebServices.OperacionesAXContenedor.ContenedorProducto[] Lineas {
            get {
                return this.LineasField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasField, value) != true)) {
                    this.LineasField = value;
                    this.RaisePropertyChanged("Lineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((this.PartidaField.Equals(value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sello1 {
            get {
                return this.Sello1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Sello1Field, value) != true)) {
                    this.Sello1Field = value;
                    this.RaisePropertyChanged("Sello1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sello2 {
            get {
                return this.Sello2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Sello2Field, value) != true)) {
                    this.Sello2Field = value;
                    this.RaisePropertyChanged("Sello2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WHSContainerId {
            get {
                return this.WHSContainerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WHSContainerIdField, value) != true)) {
                    this.WHSContainerIdField = value;
                    this.RaisePropertyChanged("WHSContainerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WHSContainerTypeCode {
            get {
                return this.WHSContainerTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WHSContainerTypeCodeField, value) != true)) {
                    this.WHSContainerTypeCodeField = value;
                    this.RaisePropertyChanged("WHSContainerTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WHSShipmentId {
            get {
                return this.WHSShipmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WHSShipmentIdField, value) != true)) {
                    this.WHSShipmentIdField = value;
                    this.RaisePropertyChanged("WHSShipmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkIdField, value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContenedorProducto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ContenedorProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesAXContenedor.IOperacionesAXContenedor")]
    public interface IOperacionesAXContenedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesAXContenedor/getContenedor", ReplyAction="http://tempuri.org/IOperacionesAXContenedor/getContenedorResponse")]
        P2PMovil.WebServices.OperacionesAXContenedor.ContenedorDatos getContenedor(string WorkID, int partida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesAXContenedor/getContenedor", ReplyAction="http://tempuri.org/IOperacionesAXContenedor/getContenedorResponse")]
        System.Threading.Tasks.Task<P2PMovil.WebServices.OperacionesAXContenedor.ContenedorDatos> getContenedorAsync(string WorkID, int partida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacionesAXContenedorChannel : P2PMovil.WebServices.OperacionesAXContenedor.IOperacionesAXContenedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesAXContenedorClient : System.ServiceModel.ClientBase<P2PMovil.WebServices.OperacionesAXContenedor.IOperacionesAXContenedor>, P2PMovil.WebServices.OperacionesAXContenedor.IOperacionesAXContenedor {
        
        public OperacionesAXContenedorClient() {
        }
        
        public OperacionesAXContenedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesAXContenedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesAXContenedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesAXContenedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public P2PMovil.WebServices.OperacionesAXContenedor.ContenedorDatos getContenedor(string WorkID, int partida) {
            return base.Channel.getContenedor(WorkID, partida);
        }
        
        public System.Threading.Tasks.Task<P2PMovil.WebServices.OperacionesAXContenedor.ContenedorDatos> getContenedorAsync(string WorkID, int partida) {
            return base.Channel.getContenedorAsync(WorkID, partida);
        }
    }
}
