//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2PMovil.WebServices.OperacionesAXOrdenSurtido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenSurtido", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class OrdenSurtido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private P2PMovil.WebServices.OperacionesAXOrdenSurtido.DetalleOT[] DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public P2PMovil.WebServices.OperacionesAXOrdenSurtido.DetalleOT[] Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNum {
            get {
                return this.OrderNumField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumField, value) != true)) {
                    this.OrderNumField = value;
                    this.RaisePropertyChanged("OrderNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkIdField, value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleOT", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DetalleOT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QtyWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QtyWork {
            get {
                return this.QtyWorkField;
            }
            set {
                if ((this.QtyWorkField.Equals(value) != true)) {
                    this.QtyWorkField = value;
                    this.RaisePropertyChanged("QtyWork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemId {
            get {
                return this.itemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.itemIdField, value) != true)) {
                    this.itemIdField = value;
                    this.RaisePropertyChanged("itemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesAXOrdenSurtido.IOperacionesAXOrdenSurtido")]
    public interface IOperacionesAXOrdenSurtido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesAXOrdenSurtido/getTrabajoSurtido", ReplyAction="http://tempuri.org/IOperacionesAXOrdenSurtido/getTrabajoSurtidoResponse")]
        P2PMovil.WebServices.OperacionesAXOrdenSurtido.OrdenSurtido getTrabajoSurtido(string OrderNum, string WorkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesAXOrdenSurtido/getTrabajoSurtido", ReplyAction="http://tempuri.org/IOperacionesAXOrdenSurtido/getTrabajoSurtidoResponse")]
        System.Threading.Tasks.Task<P2PMovil.WebServices.OperacionesAXOrdenSurtido.OrdenSurtido> getTrabajoSurtidoAsync(string OrderNum, string WorkId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacionesAXOrdenSurtidoChannel : P2PMovil.WebServices.OperacionesAXOrdenSurtido.IOperacionesAXOrdenSurtido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesAXOrdenSurtidoClient : System.ServiceModel.ClientBase<P2PMovil.WebServices.OperacionesAXOrdenSurtido.IOperacionesAXOrdenSurtido>, P2PMovil.WebServices.OperacionesAXOrdenSurtido.IOperacionesAXOrdenSurtido {
        
        public OperacionesAXOrdenSurtidoClient() {
        }
        
        public OperacionesAXOrdenSurtidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesAXOrdenSurtidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesAXOrdenSurtidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesAXOrdenSurtidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public P2PMovil.WebServices.OperacionesAXOrdenSurtido.OrdenSurtido getTrabajoSurtido(string OrderNum, string WorkId) {
            return base.Channel.getTrabajoSurtido(OrderNum, WorkId);
        }
        
        public System.Threading.Tasks.Task<P2PMovil.WebServices.OperacionesAXOrdenSurtido.OrdenSurtido> getTrabajoSurtidoAsync(string OrderNum, string WorkId) {
            return base.Channel.getTrabajoSurtidoAsync(OrderNum, WorkId);
        }
    }
}
